SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);
UPDATE oc_authtoken SET last_activity=UNIX_TIMESTAMP() WHERE id=FLOOR(RAND()*100000);
SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);
SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);
SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);
SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);
SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);
SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);
SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);
SELECT * FROM oc_authtoken WHERE id = FLOOR(RAND()*100000);